In [6]:
import numpy as np
import pandas as pd
import kmapper as km
from kmapper.jupyter import display
import sklearn

In [7]:
df1 = pd.read_csv("SOI.csv")
df2 = pd.read_csv("SOI_OLR.csv")
df3 = pd.read_csv("Full.csv")

In [8]:
data = df3[['Nino1.2','Nino3','Nino 4','Nino3.4']].to_numpy()
data

array([[24.28, 25.84, 28.01, 26.65],
       [25.38, 26.26, 27.99, 26.54],
       [25.22, 26.92, 28.18, 27.09],
       ...,
       [26.8 , 26.25, 27.58, 26.29],
       [28.12, 27.52, 28.09, 27.23],
       [28.18, 28.02, 28.81, 27.99]])

### Mapper con respecto al Nino3.4 con promedio de Nino3, Nino 4

In [9]:
mean_outer_score=(data[:,1]+data[:,2])/3.0

mapper = km.KeplerMapper(verbose=1)
# La proyección sobre Nino3.4, corresponde a proyectar sobre la CUARTA columna de data
projected_data = mapper.fit_transform(data, projection=[3] ) #Nino3.4

KeplerMapper(verbose=1)
..Composing projection pipeline of length 1:
	Projections: [3]
	Distance matrices: False
	Scalers: MinMaxScaler()
..Projecting on data shaped (496, 4)

..Projecting data using: [3]

..Scaling with: MinMaxScaler()



In [10]:
covering=km.Cover(n_cubes=4,perc_overlap=0.2)

G = mapper.map(projected_data, data, clusterer=sklearn.cluster.KMeans(n_clusters=4),cover=covering)

Mapping on data shaped (496, 4) using lens shaped (496, 1)

Creating 4 hypercubes.


c:\Users\feder\anaconda3\envs\RetoEquipo1\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\feder\anaconda3\envs\RetoEquipo1\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\feder\anaconda3\envs\RetoEquipo1\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\feder\anaconda3\envs\RetoEquipo1\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  war


Created 17 edges and 16 nodes in 0:00:00.217554.


In [11]:
G['meta_data']

{'projection': '[3]',
 'n_cubes': 4,
 'perc_overlap': 0.2,
 'clusterer': 'KMeans(n_clusters=4)',
 'scaler': 'MinMaxScaler()'}

In [12]:
mapper.visualize(G, 
                title='Performance Data based on Nino3.4 and Mean of other three',
                #custom_tooltips = performance_data['gender'].to_numpy(),
                color_values = mean_outer_score,
                color_function_name = 'Mean of Nino3 and Nino 4',
                node_color_function=np.array(['average','std','sum','max','min']))

km.jupyter.display("performance_math_score" + ".html")

Wrote visualization to: mapper_visualization_output.html


c:\Users\feder\anaconda3\envs\RetoEquipo1\lib\site-packages\kmapper\visuals.py:344: RuntimeWarning: invalid value encountered in scalar divide
  height = np.floor(((bar / max_bucket_value) * 100) + 0.5)
c:\Users\feder\anaconda3\envs\RetoEquipo1\lib\site-packages\kmapper\visuals.py:345: RuntimeWarning: invalid value encountered in scalar divide
  perc = round((bar / sum_bucket_value) * 100.0, 1)


c:\Users\feder\anaconda3\envs\RetoEquipo1\lib\site-packages\IPython\core\display.py:419: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")


### Mapper con respecto Anom3.4 con promedio de OLR y SOI

In [20]:
data1 = df3[['Anom3.4','OLR','SOI']].to_numpy()
data1

array([[ 0.08,  0.9 ,  1.2 ],
       [-0.2 ,  0.1 ,  0.3 ],
       [-0.14, -0.6 ,  0.6 ],
       ...,
       [-0.44,  1.4 ,  1.4 ],
       [-0.01,  1.4 ,  0.2 ],
       [ 0.1 ,  0.6 ,  0.  ]])

In [21]:
mean_outer_score1=(data1[:,1]+data1[:,2])/2.0

mapper1 = km.KeplerMapper(verbose=1)
# La proyección sobre Anom3.4, corresponde a proyectar sobre la PRIMER columna de data
projected_data1 = mapper1.fit_transform(data1, projection=[0] ) #Anom3.4

KeplerMapper(verbose=1)
..Composing projection pipeline of length 1:
	Projections: [0]
	Distance matrices: False
	Scalers: MinMaxScaler()
..Projecting on data shaped (496, 3)

..Projecting data using: [0]

..Scaling with: MinMaxScaler()



In [22]:
covering1=km.Cover(n_cubes=4,perc_overlap=0.2)

G1 = mapper1.map(projected_data1, data1, clusterer=sklearn.cluster.KMeans(n_clusters=4),cover=covering1)

Mapping on data shaped (496, 3) using lens shaped (496, 1)

Creating 4 hypercubes.

Created 17 edges and 16 nodes in 0:00:00.184278.


c:\Users\patog\miniconda3\envs\py3.8\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\patog\miniconda3\envs\py3.8\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\patog\miniconda3\envs\py3.8\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\patog\miniconda3\envs\py3.8\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [23]:
G1['meta_data']

{'projection': '[0]',
 'n_cubes': 4,
 'perc_overlap': 0.2,
 'clusterer': 'KMeans(n_clusters=4)',
 'scaler': 'MinMaxScaler()'}

In [24]:
mapper1.visualize(G1, 
                title='Performance Data based on Anom3.4 and Mean of other TWO',
                #custom_tooltips = performance_data['gender'].to_numpy(),
                color_values = mean_outer_score1,
                color_function_name = 'Mean of OLR and SOI',
                node_color_function=np.array(['average','std','sum','max','min']))

km.jupyter.display("performance_math_score" + ".html")

Wrote visualization to: mapper_visualization_output.html


c:\Users\patog\miniconda3\envs\py3.8\lib\site-packages\IPython\core\display.py:419: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")


### Mapper con promedio de OLR y SOI con respecto a Anom3.4

In [27]:
data1 = df3[['Anom3.4','OLR','SOI']]
df3['promedio_OS'] = (df3.OLR + df3.SOI)/2
data1 = df3[['Anom3.4', 'promedio_OS']].to_numpy()
data1

array([[ 0.08      ,  1.05      ],
       [-0.2       ,  0.2       ],
       [-0.14      ,  0.        ],
       [ 0.02      ,  0.05      ],
       [ 0.49      ,  0.05      ],
       [ 0.65      , -0.6       ],
       [ 0.27      , -1.35      ],
       [ 0.86      , -1.65      ],
       [ 1.24      , -1.55      ],
       [ 1.73      , -1.75      ],
       [ 1.68      , -2.3       ],
       [ 2.21      , -1.55      ],
       [ 2.13      , -2.5       ],
       [ 1.81      , -2.15      ],
       [ 1.22      , -1.15      ],
       [ 0.68      , -0.3       ],
       [ 0.68      , -0.1       ],
       [ 0.45      , -0.45      ],
       [-0.33      , -0.8       ],
       [-0.44      ,  0.        ],
       [-0.38      ,  0.4       ],
       [-1.02      ,  0.35      ],
       [-1.29      ,  0.05      ],
       [-1.16      ,  0.55      ],
       [-0.96      ,  0.95      ],
       [-0.16      ,  1.4       ],
       [-0.52      ,  0.5       ],
       [-0.54      ,  0.7       ],
       [-0.69      ,

In [28]:
#mean_outer_score1=(data1[:,1]+data1[:,2])/2.0

mapper1 = km.KeplerMapper(verbose=1)
# La proyección sobre Anom3.4, corresponde a proyectar sobre la PRIMER columna de data
projected_data1 = mapper1.fit_transform(data1, projection=[1] ) #promedio_OS

KeplerMapper(verbose=1)
..Composing projection pipeline of length 1:
	Projections: [1]
	Distance matrices: False
	Scalers: MinMaxScaler()
..Projecting on data shaped (496, 2)

..Projecting data using: [1]

..Scaling with: MinMaxScaler()



In [29]:
covering1=km.Cover(n_cubes=4,perc_overlap=0.2)

G1 = mapper1.map(projected_data1, data1, clusterer=sklearn.cluster.KMeans(n_clusters=4),cover=covering1)

Mapping on data shaped (496, 2) using lens shaped (496, 1)

Creating 4 hypercubes.

Created 11 edges and 16 nodes in 0:00:00.144762.


c:\Users\feder\anaconda3\envs\RetoEquipo1\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\feder\anaconda3\envs\RetoEquipo1\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\feder\anaconda3\envs\RetoEquipo1\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
c:\Users\feder\anaconda3\envs\RetoEquipo1\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  war

In [30]:
G1['meta_data']

{'projection': '[1]',
 'n_cubes': 4,
 'perc_overlap': 0.2,
 'clusterer': 'KMeans(n_clusters=4)',
 'scaler': 'MinMaxScaler()'}

In [31]:
mapper1.visualize(G1, 
                title='Performance Data based on Mean of other TWO and Anom3.4',
                #custom_tooltips = performance_data['gender'].to_numpy(),
                color_values = data1[:,0],
                color_function_name = 'Anom3.4',
                node_color_function=np.array(['average','std','sum','max','min']))

km.jupyter.display("performance_math_score" + ".html")

Wrote visualization to: mapper_visualization_output.html


c:\Users\feder\anaconda3\envs\RetoEquipo1\lib\site-packages\IPython\core\display.py:419: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")
